export const CHARITY_CATEGORIES = [
  'All Categories',
  'Youth & Grassroots',
  'Veterans & Adaptive Sports',
  'Health & Mental Wellbeing',
  'Environmental & Conservation',
  'Community Outreach',
];

export const INITIAL_CHARITIES = [
  {
    id: 'charity-1',
    name: 'Fairways for Youth',
    slug: 'fairways-for-youth',
    category: 'Youth & Grassroots',
    description: 'Empowering disadvantaged young people through golf mentoring, junior equipment grants, and life skills coaching across underserved communities.',
    missionStatement: 'Breaking down social and economic barriers to open the game of golf to thousands of underprivileged youth every year.',
    logoUrl: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=1200&auto=format&fit=crop&q=80',
    featured: true,
    totalRaised: 18450.0,
    supporterCount: 420,
    websiteUrl: 'https://fairwaysforyouth.org',
    events: [
      {
        id: 'event-1',
        title: 'Junior Masters Charity Golf Day 2026',
        date: '2026-04-18',
        location: 'Woburn Golf Club, Milton Keynes',
        description: '18-hole scramble tournament pairing juniors with tour pros, followed by charity auction and dinner.',
        eventType: 'golf_day',
      },
      {
        id: 'event-2',
        title: 'Summer Youth Skills Clinic',
        date: '2026-06-12',
        location: 'The Belfry, Sutton Coldfield',
        description: 'Interactive coaching day for 100 new youth players with PGA certified instructors.',
        eventType: 'tournament',
      },
    ],
    createdAt: '2025-01-15T00:00:00.000Z',
  },
  {
    id: 'charity-2',
    name: 'Hero Wings & Adaptive Golf',
    slug: 'hero-wings-adaptive-golf',
    category: 'Veterans & Adaptive Sports',
    description: 'Rehabilitating wounded military veterans and adaptive athletes through specialized golf equipment, therapeutic coaching, and community support.',
    missionStatement: 'Restoring confidence, mobility, and camaraderie to injured service personnel on the golf course.',
    logoUrl: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=1200&auto=format&fit=crop&q=80',
    featured: true,
    totalRaised: 24780.0,
    supporterCount: 560,
    websiteUrl: 'https://herowingsadaptive.org',
    events: [
      {
        id: 'event-3',
        title: 'Armed Forces Cup Invitational',
        date: '2026-05-24',
        location: 'Celtic Manor Resort, Newport',
        description: 'Annual celebrity and veteran Ryder-cup style charity match.',
        eventType: 'golf_day',
      },
    ],
    createdAt: '2025-02-01T00:00:00.000Z',
  },
  {
    id: 'charity-3',
    name: 'Green Greens Foundation',
    slug: 'green-greens-foundation',
    category: 'Environmental & Conservation',
    description: 'Pioneering ecological preservation, native biodiversity, and zero-chemical water stewardship on community open spaces and golf courses.',
    missionStatement: 'Transforming sporting landscapes into flourishing ecological sanctuaries and wildlife corridors.',
    logoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80',
    featured: true,
    totalRaised: 14200.0,
    supporterCount: 310,
    websiteUrl: 'https://greengreens.org',
    events: [
      {
        id: 'event-4',
        title: 'Eco-Links Tree Planting Golf Day',
        date: '2026-04-30',
        location: 'Royal St George’s, Sandwich',
        description: 'Planting 500 indigenous trees along coastal links followed by an ecological sustainability forum.',
        eventType: 'golf_day',
      },
    ],
    createdAt: '2025-03-01T00:00:00.000Z',
  },
  {
    id: 'charity-4',
    name: 'Mind Over Fairway',
    slug: 'mind-over-fairway',
    category: 'Health & Mental Wellbeing',
    description: 'Harnessing outdoor recreation, mindful movement, and peer support networks to combat isolation and promote positive mental health.',
    missionStatement: 'Providing evidence-based mental health peer groups and outdoor wellness days.',
    logoUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=1200&auto=format&fit=crop&q=80',
    featured: false,
    totalRaised: 11950.0,
    supporterCount: 280,
    websiteUrl: 'https://mindoverfairway.org',
    events: [
      {
        id: 'event-5',
        title: 'Sunrise Walk & Play Fundraiser',
        date: '2026-07-10',
        location: 'Sunningdale Golf Club, Berkshire',
        description: 'Dawn walking round focusing on mindfulness and mental resilience.',
        eventType: 'golf_day',
      },
    ],
    createdAt: '2025-03-10T00:00:00.000Z',
  },
  {
    id: 'charity-5',
    name: 'Community Care & Relief Hub',
    slug: 'community-care-relief-hub',
    category: 'Community Outreach',
    description: 'Providing crisis food parcels, warm community hubs, and hardship grants to families facing acute economic adversity.',
    missionStatement: 'Ensuring no family is left behind in times of sudden financial hardship.',
    logoUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1200&auto=format&fit=crop&q=80',
    featured: false,
    totalRaised: 19800.0,
    supporterCount: 470,
    websiteUrl: 'https://communitycarehub.org',
    events: [
      {
        id: 'event-6',
        title: 'Annual Charity Gala & Silent Auction',
        date: '2026-08-15',
        location: 'The Dorchester, London',
        description: 'Evening gala with guest speakers and live entertainment to raise emergency relief funds.',
        eventType: 'gala',
      },
    ],
    createdAt: '2025-03-15T00:00:00.000Z',
  },
];
